// Services/RouteService.cs

using backendDistributor.Models;
using backendDistributor.Services;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using SqlRoute = backendDistributor.Models.Route; // <-- THE FIX IS HERE

public class RouteService
{
    private readonly CustomerDbContext _context;
    private readonly SapService _sapService;
    private readonly ILogger<RouteService> _logger;
    private readonly string _dataSource;

    public RouteService(CustomerDbContext context, SapService sapService, IConfiguration configuration, ILogger<RouteService> logger)
    {
        _context = context;
        _sapService = sapService;
        _logger = logger;
        _dataSource = configuration.GetValue<string>("DataSource");
    }

    // --- GET ALL ROUTES ---
    public async Task<IEnumerable<RouteNode>> GetAllAsync()
    {
        if (_dataSource?.ToUpper() == "SAP")
        {
            _logger.LogInformation("--> RouteService is using SAP data for GET.");
            // This is the complex tree-building logic moved from your old controller
            var sapJsonResult = await _sapService.GetRoutesAsync();
            using var jsonDoc = JsonDocument.Parse(sapJsonResult);
            if (!jsonDoc.RootElement.TryGetProperty("value", out var sapRouteElements)) { return new List<RouteNode>(); }

            var allNodes = new Dictionary<int, RouteNode>();
            foreach (var element in sapRouteElements.EnumerateArray())
            {
                if (element.TryGetProperty("TerritoryID", out var id) && element.TryGetProperty("Description", out var desc))
                {
                    var node = new RouteNode { Id = id.GetInt32(), Name = desc.GetString() ?? "", Children = new List<RouteNode>() };
                    allNodes[node.Id] = node;
                }
            }
            // (The rest of your tree-building and flattening logic would go here if needed)
            // For now, we return a simple flat list which is what your React app expects.
            return allNodes.Values.OrderBy(r => r.Name).ToList();
        }
        else
        {
            _logger.LogInformation("--> RouteService is using SQL data for GET.");
            // We read from the SQL 'Routes' table and convert it to the 'RouteNode' format.
            return await _context.Routes
                .OrderBy(r => r.Name)
                .Select(r => new RouteNode { Id = r.Id, Name = r.Name })
                .ToListAsync();
        }
    }

    // --- ADD A ROUTE ---
    public async Task<RouteNode> AddAsync(RouteNode route)
    {
        if (_dataSource?.ToUpper() == "SAP")
        {
            _logger.LogInformation("--> RouteService is using SAP data for POST.");
            var payload = new { name = route.Name };
            using var doc = JsonDocument.Parse(JsonSerializer.Serialize(payload));
            var routeData = doc.RootElement.Clone();
            var createdRouteJson = await _sapService.CreateRouteAsync(routeData);

            using var jsonDoc = JsonDocument.Parse(createdRouteJson);
            return new RouteNode
            {
                Id = jsonDoc.RootElement.GetProperty("TerritoryID").GetInt32(),
                Name = jsonDoc.RootElement.GetProperty("Description").GetString() ?? ""
            };
        }
        else
        {
            _logger.LogInformation("--> RouteService is using SQL data for POST.");
            var newSqlRoute = new SqlRoute { Name = route.Name }; // <-- AND THE FIX IS HERE
            _context.Routes.Add(newSqlRoute);
            await _context.SaveChangesAsync();
            route.Id = newSqlRoute.Id; // Update the ID with the one generated by SQL
            return route;
        }
    }

    // --- UPDATE A ROUTE ---
    public async Task UpdateAsync(int id, RouteNode route)
    {
        if (_dataSource?.ToUpper() == "SAP")
        {
            _logger.LogInformation("--> RouteService is using SAP data for UPDATE.");
            var payload = new { Description = route.Name };
            using var doc = JsonDocument.Parse(JsonSerializer.Serialize(payload));
            var routeData = doc.RootElement.Clone();
            await _sapService.UpdateRouteAsync(id, routeData);
        }
        else
        {
            _logger.LogInformation("--> RouteService is using SQL data for UPDATE.");
            var sqlRoute = await _context.Routes.FindAsync(id);
            if (sqlRoute == null) throw new KeyNotFoundException($"Route with ID {id} not found in SQL.");
            sqlRoute.Name = route.Name;
            _context.Routes.Update(sqlRoute);
            await _context.SaveChangesAsync();
        }
    }

    // --- DELETE A ROUTE ---
    public async Task DeleteAsync(int id)
    {
        if (_dataSource?.ToUpper() == "SAP")
        {
            _logger.LogInformation("--> RouteService is using SAP data for DELETE.");
            await _sapService.DeleteRouteAsync(id);
        }
        else
        {
            _logger.LogInformation("--> RouteService is using SQL data for DELETE.");
            var sqlRoute = await _context.Routes.FindAsync(id);
            if (sqlRoute == null) throw new KeyNotFoundException($"Route with ID {id} not found in SQL.");
            _context.Routes.Remove(sqlRoute);
            await _context.SaveChangesAsync();
        }
    }
}